//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jsondecoder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessTokenResponse {
            get {
                return ((string)(this["AccessTokenResponse"]));
            }
            set {
                this["AccessTokenResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n\t\"Periods\": [{\r\n\t\t\"Id\": \"1bec6825-c7f0-42e5-9b1c-e1ba1dd1991b\",\r\n\t\t\"ProjectId\"" +
            ": \"aeaed2c6-8648-4c06-8189-683c3ecc1ec3\",\r\n\t\t\"TimeZone\": \"Egypt Standard Time\",\r" +
            "\n\t\t\"DateStart\": \"2024-02-15T14:31:40.7868998+02:00\",\r\n\t\t\"DateEnd\": \"2024-02-15T1" +
            "5:21:40.7868998+02:00\",\r\n\t\t\"DateIntervalStart\": \"2024-02-15T14:31:40.7988998+02:" +
            "00\",\r\n\t\t\"Duration\": 3000.0,\r\n\t\t\"DateLastActive\": \"2024-02-15T15:21:40.7988998+02" +
            ":00\",\r\n\t\t\"SessionId\": \"win_b2b4b422-bd8b-46ef-8289-6b885cabc906\",\r\n\t\t\"Activitys\"" +
            ": [{\r\n\t\t\t\"Data\": \"11111\",\r\n\t\t\t\"Date\": \"2024-02-15T11:40:00Z\",\r\n\t\t\t\"Type\": null\r\n" +
            "\t\t}, {\r\n\t\t\t\"Data\": \"11111111111111111111111111111111111111111111\",\r\n\t\t\t\"Date\": \"" +
            "2024-02-15T11:40:00Z\",\r\n\t\t\t\"Type\": null\r\n\t\t}, {\r\n\t\t\t\"Data\": \"1111111111111111\",\r" +
            "\n\t\t\t\"Date\": \"2024-02-15T11:50:00Z\",\r\n\t\t\t\"Type\": null\r\n\t\t}, {\r\n\t\t\t\"Data\": \"111111" +
            "11111111111111111111111111111111111111\",\r\n\t\t\t\"Date\": \"2024-02-15T11:50:00Z\",\r\n\t\t" +
            "\t\"Type\": null\r\n\t\t}, {\r\n\t\t\t\"Data\": \"1111111111111111\",\r\n\t\t\t\"Date\": \"2024-02-15T12" +
            ":00:00Z\",\r\n\t\t\t\"Type\": null\r\n\t\t}, {\r\n\t\t\t\"Data\": \"1111111111111111111111111111\",\r\n" +
            "\t\t\t\"Date\": \"2024-02-15T12:00:00Z\",\r\n\t\t\t\"Type\": null\r\n\t\t}],\r\n\t\t\"AppTime\": [{\r\n\t\t\t" +
            "\"PeriodId\": \"1bec6825-c7f0-42e5-9b1c-e1ba1dd1991b\",\r\n\t\t\t\"ApplicationName\": \"webs" +
            "torm64\",\r\n\t\t\t\"Duration\": 498.3785364999999,\r\n\t\t\t\"Date\": \"2024-02-15T11:40:00Z\"\r\n" +
            "\t\t}, {\r\n\t\t\t\"PeriodId\": \"1bec6825-c7f0-42e5-9b1c-e1ba1dd1991b\",\r\n\t\t\t\"ApplicationN" +
            "ame\": \"webstorm64\",\r\n\t\t\t\"Duration\": 599.3847091000001,\r\n\t\t\t\"Date\": \"2024-02-15T1" +
            "1:50:00Z\"\r\n\t\t}, {\r\n\t\t\t\"PeriodId\": \"1bec6825-c7f0-42e5-9b1c-e1ba1dd1991b\",\r\n\t\t\t\"A" +
            "pplicationName\": \"webstorm64\",\r\n\t\t\t\"Duration\": 432.02577990000015,\r\n\t\t\t\"Date\": \"" +
            "2024-02-15T12:00:00Z\"\r\n\t\t}, {\r\n\t\t\t\"PeriodId\": \"1bec6825-c7f0-42e5-9b1c-e1ba1dd19" +
            "91b\",\r\n\t\t\t\"ApplicationName\": \"Windows Explorer\",\r\n\t\t\t\"Duration\": 4.0066974,\r\n\t\t\t" +
            "\"Date\": \"2024-02-15T12:00:00Z\"\r\n\t\t}],\r\n\t\t\"DownTime\": null,\r\n\t\t\"Note\": null,\r\n\t\t\"" +
            "RemoveDowntime\": null,\r\n\t\t\"DateSave\": \"2024-02-15T15:21:40.7868998+02:00\",\r\n\t\t\"B" +
            "illable\": false,\r\n\t\t\"Completed\": null,\r\n\t\t\"IsMeetingTime\": null\r\n\t}],\r\n\t\"Notes\":" +
            " null\r\n}")]
        public string PeroidJson {
            get {
                return ((string)(this["PeroidJson"]));
            }
            set {
                this["PeroidJson"] = value;
            }
        }
    }
}
